### ISSUE TITLE
Bug repeat: E121: Undefined variable: b:doge_supported_doc_standards

### ISSUE THREAD

**Issue by thevan96** [kkoomen/vim-doge#620] opened 2023-09-12 03:04 UTC
1. init.vim with config doge
```vim
Plug 'kkoomen/vim-doge', { 'do': { -> doge#install() } }
nmap <silent> <leader>D <Plug>(doge-generate)
```
2. Test whether you can still run into the problem.
```
Error detected while processing function doge#generate:
line    2:
E121: Undefined variable: b:doge_supported_doc_standards
E116: Invalid arguments for function index
```
 I use neovim 0.9.1

**Comment by kkoomen** [comment] 2023-09-17 15:51
Hi,

Please provide me with more information regarding how to reproduce this issue, because your issue lacks a lot of information that I need for the sake of debugging this issue.

Please provide me something like:
- `nvim -u doge.vim test.js`
- use the function `function foo(bar) {}`
- run `:DogeGenerate jsdoc`

Otherwise I'll close this issue.

**Comment by thevan96** [comment] 2023-09-17 16:26
I recorded it, maybe this will be helpful for you
![Peek 2023-09-17 23-24](https://github.com/kkoomen/vim-doge/assets/47932916/7d4cb2e6-eece-4870-874f-8f15150463f4)

**Comment by kkoomen** [comment] 2023-09-18 07:45
Hi,

Thanks a lot, that helps a lot!

First of all, the problem in the image below is a nvim problem they have to fix, see #358 
<img width="742" alt="image" src="https://github.com/kkoomen/vim-doge/assets/10693490/0713e018-a98e-47af-b7b3-f7f0513b97a1">

Second, if you open `test.js`, what is the output of `:echo &ft`? It should be `javascript`. If it's not javascript, let me know what it is, because it should then load `~/.local/share/nvim/plugged/vim-doge/ftplugin/javascript.vim`. Can you also try to put an `echoerr "TEST"` inside `ftplugin/javascript.vim` and see if you open `test.js` whether you'll see the error message.

**Comment by thevan96** [comment] 2023-09-18 12:45
Value of `echo &ft` is `javascript` and `echoerr "TEST"` not show
![now](https://github.com/kkoomen/vim-doge/assets/47932916/c8bf0654-d8fa-4b12-aad1-1cc845b67099)

**Closed** 2023-09-18 12:55 UTC
Labels: bug

**Comment by kkoomen** [comment] 2023-09-19 16:29
@thevan96 Ah, that explains a lot. Not sure if you're new to vim, but `filetype plugin indent off` is something you should always have set. Nonetheless, it shouldn't break vim-doge or regular vim usage, so I'll fix this. Thanks for finding and reporting this behavior!
