### ISSUE TITLE
Support using Doge as a backend for snippet plugins like Ultisnips

### ISSUE THREAD

**Issue by idanarye** [kkoomen/vim-doge#16] opened 2019-07-18 14:11 UTC
**Is your feature request related to a problem? Please describe.**

[As mentioned in the README](https://github.com/kkoomen/vim-doge#jump-forward-trigger-requires-to-be-pressed-2-times-in-order-to-jump-forward), Doge's key bindings can interfere with Ultisnips. The various solutions are suboptimal - we should have a uniform snippets experience regardless of the snippet's source.

**Describe the solution you'd like**
Doge should offer a configuration variable for a function reference that will accept the documentation comment snippet and a location to put it (since, depending on the language, this could be below or above the function, and since the function can span multiple lines). The default should be Doge's own built-in snippets UI, but it would be nice if Doge would come with implementation of such function for common snippet frontends like Ultisnips and [coc-snippets](https://github.com/neoclide/coc-snippets/issues/44) (and SnipMate, if it supports anonymous snippets)

**Describe alternatives you've considered**
Alternatively, Doge could offer a function that just returns the docstring snippet and its desired location, and we could call it to get that data and pass it to the snippet UI.

**Comment by kkoomen** [comment] 2019-07-18 14:23
Hi

I do agree! I literally turned off UltiSnips locally because of the plugins clashing into each other, but the problem I've currently experienced is what I've described [in the README](https://github.com/kkoomen/vim-doge#jump-forward-trigger-requires-to-be-pressed-2-times-in-order-to-jump-forward).

I do think the problem is fixable, so I'll work on it tomorrow.

Is there any other unwanted behavior you're experiencing with UltiSnips + DoGe? If so, I'd like to know this so I can fix this all at once.

**Comment by idanarye** [comment] 2019-07-18 14:32
Actually, I'm using coc-snippets myself - I mentioned Ultisnips because you mentioned it as conflicting in the README. I've mapped `<C-j>` and `<C-k>` to forward and backward to have a similar behavior, but there are tiny differences that tend to irritate.

**Comment by kkoomen** [comment] 2019-07-18 14:52
>I'm using coc-snippets myself

Are you having any issues related to coc-snippets?

>I've mapped <C-j> and <C-k> to forward and backward

In DoGe or in coc-snippets?

>(...) there are tiny differences that tend to irritate.

Are they related to DoGe? If so, please note them down so I can check whether it's fixable by DoGe or not.

**Comment by idanarye** [comment] 2019-07-18 15:03
> > I've mapped `<C-j>` and `<C-k>` to forward and backward
>
> In DoGe or in coc-snippets?

In DoGe - with coc-snippets these keys are the default.

My main irritation is that with DoGe typing `<C-j>` on the last placeholder creates a new line, and on coc-snippets it doesn't. I assume this is not really a conflict (because that's `<C-j>`'s behavior in insert mode when you don't deal with a snippet) and if I wasn't using coc-snippets I wouldn't mind because this behavior is kind of expected, but the thing that irritates me is that I'm getting different behavior based on the source of the snippet.

I don't really think you should try so hard to match DoGe's behavior to that of some other plugin (which plugin? I assume Ultisnip, SnipMate and coc-snippets have other subtle differneces - which one should DoGe mimic?). I think it's better to just allow interfacing with the main snippets plugins.

**Comment by kkoomen** [comment] 2019-07-20 01:42
Since it's not possible in Vim to map two functions to the same keystroke I won't fix this for now. UltiSnips is overwriting DoGe so this can't be fixed from my side I think.

Feel free to submit any new issues if you experience any unwanted behaviour in the future. Thanks for your contribution.

**Closed by kkoomen** 2019-07-20 01:42 UTC
Labels: enhancement, good first issue

**Comment by kkoomen** [comment] 2019-09-11 13:21
@idanarye I think #44 fixed your issue. Can you confirm this?
