### ISSUE TITLE
DoGe accidentally causes attaches `tsserver` on `vue` files

### ISSUE THREAD

**Issue by rensftw** [kkoomen/vim-doge#324] opened 2022-03-19 00:37 UTC
Note: Thanks for this great plugin! I've been using it for a while and find it quite useful. 
Thought I'd document this in case anyone else runs into it, because I couldn't find anything similar to this issue by googling.

**Describe the bug**
I am using Neovim with [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) and frequently edit Vue files.
I noticed that at some point `tsserver` started getting attached to `.vue` files  resulting in a bunch of invalid errors (screenshot below). This is highly unusual, because [`tsserver` ignores `.vue` filetypes by default](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#tsserver).

This took a while diagnose, but I think I finally found the culprit:
```vim
let g:doge_filetype_aliases = {
\  'javascript': ['vue']
\}
```
It appears that with this configuration DoGe causes `tsserver` to get attached to `.vue` files (which it's supposed to ignore). 
My guess is that DoGe accidentally interferes with either`nvim-lspconfig`/LSP client attachment or, most likely, with Neovim's filetype determination.
Removing `vue` from the `javascript` DoGe aliases resolves the issue and `tsserver` no longer gets attached to `.vue` files.

**Settings**
<details><summary><code>doge-rc.lua</code></summary>
<p>

 ```lua
vim.g.doge_mapping = '<leader>jd'
vim.g.doge_filetype_aliases = {
    javascript = {
        'vue',
        'javascript.jsx',
        'javascriptreact',
        'javascript.tsx',
        'typescriptreact',
        'typescript',
        'typescript.tsx',
    }
}
vim.g.doge_javascript_settings = {
    destructuring_props = 1,
    omit_redundant_param_types = 0,
}


 ```

</p>
</details>

**To Reproduce**
(Using [`nvim-lspconfig`'s `minimal_init.lua` as boilerplate](https://github.com/neovim/nvim-lspconfig/blob/master/test/minimal_init.lua) and added the minimally required components)
<details><summary><code>minimal_init.lua</code></summary>
<p>

```lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local install_path = join_paths(package_root, 'packer', 'start', 'packer.nvim')
local compile_path = join_paths(install_path, 'plugin', 'packer_compiled.lua')

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
      'kkoomen/vim-doge',
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  }
end

-- DoGe filetype aliases: this causes tsserver to get attached to vue files
-- Remove vue from the table to see the issue resolved
vim.g.doge_filetype_aliases = {
    javascript = {
        'vue',
        'javascript.jsx',
        'javascriptreact',
        'javascript.tsx',
        'typescriptreact',
        'typescript',
        'typescript.tsx',
    }
}

_G.load_config = function()
  vim.lsp.set_log_level 'trace'
  local nvim_lsp = require 'lspconfig'
  -- Add the server that troubles you here
  local name = 'tsserver'
  local cmd = { "typescript-language-server", "--stdio" } -- default command
  if not name then
    print 'You have not defined a server name, please edit minimal_init.lua'
  end
  if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
    print [[You have not defined a server default cmd for a server
      that requires it please edit minimal_init.lua]]
  end

  nvim_lsp[name].setup {
    cmd = cmd,
    on_attach = function() end,
  }

  print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
```

</p>
</details>

<details><summary><code>minimal_example.vue</code></summary>
<p>

```vue
<template>
  <router-view />
</template>

<style>
  body {
    overflow: hidden;
  }
</style>
```

</p>
</details>

1. Install Neovim and  [Packer](https://github.com/wbthomason/packer.nvim)
2. Use the `minimal_init.lua` config from above
3. Open a `.vue` file (such as the example I provided)
4. There will be a lot of invalid errors like the ones from the screenshot below
5. `:LspInfo` will show that `tsserver` is attached to the buffer 
6. When you remove `vue` from the `vim.g.doge_filetype_aliases.javascript` table and re-open the `.vue` file, the errors are gone and `tsserver` is not attached to the buffer

**Expected behavior**
Adding `vue` as a DoGe alias should not cause `tsserver` to be attached to `.vue` files.

**Screenshots**
Screenshot of when a rogue `tsserver` gets attached to a `.vue` file because of DoGe aliases:
<img width="567" alt="image" src="https://user-images.githubusercontent.com/22574186/159098184-ee94a6ac-73c0-4bf9-8e74-cc294b720b18.png">

**Output of `vim --version`**
```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local
```

**Comment by AlexisFinn** [comment] 2022-04-27 14:03
:+1: having exactly the same issue, preventing me from using this plugin with `vue` files.
Any progress ?

**Comment by kkoomen** [comment] 2022-05-01 13:27
So, after I've did some testing, this seems to be NVIM specific. However, you did mention the following:

>  Adding `vue` as a DoGe alias should not cause `tsserver` to be attached to `.vue` files.

but this is not how things work in DoGe. When you're using the configuration you're using for `g:doge_filetype_aliases`, you're basically saying that DoGe should treat `vue` files the same as JavaScript files (basically allowing to generate JS docs for functions there). If you enable this, then you do need the tsserver in order to generate documentation. You can't say that DoGe should be enabled on that filetype, but then disabling the tsserver, because then you can't generate any documentation at all, therefore you should simply _not_ specify `vue` as an alias for the `javascript` filetype.

Can you clarify what you expect DoGe to do in this situation?

**Comment by AlexisFinn** [comment] 2022-05-02 16:29
If I launch `:LspInfo` on a `Vue` file:
![2022-05-02-182231_953x528_scrot](https://user-images.githubusercontent.com/7420883/166269946-ad4c1ec9-f24e-475e-8070-88daf458b591.png)

If I add this to my vim config:
```lua
vim.g.doge_filetype_aliases = {
  javascript = {'vue'}
}
```
and then launch `:LspInfo` on the same file:
![2022-05-02-182205_910x705_scrot](https://user-images.githubusercontent.com/7420883/166270115-38ab9a19-805a-43fe-968f-3977e61f32e9.png)
So somehow NVIM's builtin Lsp seems to have taken into account the doge configuration because it's now also attaching `tsserver` to the file as if it was a javascript file..
Note that it is still using `vuels` so somehow it now considers this file as being both a `vue` file and a `javascript` file.

As for the expected behavior, I would expect the doge configuration to not affect Lsp in any way.

**Comment by kkoomen** [comment] 2022-05-02 18:41
@AlexisFinn I think I know what's happening. So basically when you use the config for `g:doge_filetype_aliases` saying that `vue` is an alias for `javascript`, the `javascript` filetype is invoked from vim-doge when you open a vue file.

If you open a `test.js` or `test.ts` file and then run `:LspInfo`, do you also see the `tsserver` running? If so, then this is expected behavior.

**Comment by AlexisFinn** [comment] 2022-05-02 21:16
@kkoomen Yes, `tsserver` should be running for javascript and typescript files as that's what I configured. But I specifically don't want it running for `vue` files has `vuels` is taking care of those. I wouldn't expect Doge to affect this, I would expect the filetype alias to only be taken into account by doge and not other plugins. But if you say this is normal behavior ok, I suppose it's not a bug but more of a feature request.

Anyway thank you for looking into this.

**Comment by kkoomen** [comment] 2022-05-02 23:16
> @kkoomen Yes, `tsserver` should be running for javascript and typescript files as that's what I configured. But I specifically don't want it running for `vue` files has `vuels` is taking care of those. I wouldn't expect Doge to affect this, I would expect the filetype alias to only be taken into account by doge and not other plugins. But if you say this is normal behavior ok, I suppose it's not a bug but more of a feature request.
> 
> 
> 
> Anyway thank you for looking into this.

This is indeed expected behavior. As I said, you're basically telling vim-doge to use vue files in the same way as JavaScript files, hence the configuration variable is called "alias", because that's what you're doing when you're aliasing vue to JavaScript.

This is an issue that you should solve on your end. I'll close this issue for now. Thank you for the fast replies.

**Closed** 2022-05-02 23:16 UTC
Labels: bug
