### ISSUE TITLE
Javascript Generation Issue

### ISSUE THREAD

**Issue by TaylorBeeston** [kkoomen/vim-doge#106] opened 2020-10-11 15:09 UTC
**Describe the bug**
Since v2, generating jsdoc strings for functions that are directly below another function has given me issues with "swallowing" the above function's closing curly brace.

![swallow](https://user-images.githubusercontent.com/39720479/95682216-f64b5a00-0b98-11eb-82ce-3b920a37a6f6.png)

 Hitting `u` immediately after generation pretty reliably fixes the issue, but it would be nice to try and figure out *why* this is happening and then fix it!

**Settings**
default

**To Reproduce**

See https://asciinema.org/a/4zoxqz5d71o53kyep8ko518W7

**Expected behavior**
Regular JSDoc string generation

**Screenshots**
[Asciinema](https://asciinema.org/a/4zoxqz5d71o53kyep8ko518W7) (Please ignore the gql server warnings when opening the file, those are unrelated, and the "Typescript parser failed" warnings have been documented in #105)

![neofetch](https://user-images.githubusercontent.com/39720479/95681978-b59f1100-0b97-11eb-8b73-7591923c3a70.png)

**Out of `vim --version`**
```bash
❯ nvim --version
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by kkoomen** [comment] 2020-10-11 15:44
@TaylorBeeston You've linked the wrong asciinema video. Could you edit it and add the proper one with a demo of how you've reproduced it? Also, I suggest you change your resolution to a 16:9, because I have trouble to view the video demo properly.

**Comment by TaylorBeeston** [comment] 2020-10-11 15:47
Whoops! Sorry about that. I updated the links. I'm away from my computer for a while, but I can re-record them for you tonight!

**Comment by TaylorBeeston** [comment] 2020-10-12 03:05
I went ahead and rerecorded the Asciinemas and updated the links. They should be much easier to see now!

**Comment by kkoomen** [comment] 2020-10-12 04:52
@TaylorBeeston Thanks, I'll have a look soon.

**Comment by kkoomen** [comment] 2020-10-12 12:36
There must be something else happening in your vimrc because I can't reproduce this with a minimal vimrc:

- Create `doge.vim` with the following contents:

```vim
set nocompatible
set runtimepath^=/path/to/vim-doge
filetype plugin indent on
syntax on
set hidden
```

and then do: `vim -u doge.vim test.js` with the following contents:

```js
const test1 = () => {
  return 5;
}

const test2 = () => {
  return 5;
}

function test3() {
  return 5;
}
```

All of them result in this perfectly (both vim and neovim have no problem):

```js
/**
 * [TODO:description]
 *
 * @return {[TODO:type]} [TODO:description]
 */
const test1 = () => {
  return 5;
}

/**
 * [TODO:description]
 *
 * @return {[TODO:type]} [TODO:description]
 */
const test2 = () => {
  return 5;
}

/**
 * [TODO:description]
 *
 * @return {[TODO:type]} [TODO:description]
 */
function test3() {
  return 5;
}
```

**Comment by kkoomen** [comment] 2020-10-12 12:36
Since my tests don't fail and I can't reproduce it, I'll close it. Feel free to comment the solution later if you've found it.

**Closed by kkoomen** 2020-10-12 12:36 UTC
Labels: bug

**Comment by TaylorBeeston** [comment] 2020-10-12 12:53
@kkoomen no worries! Reproducing it as you have outlined causes it to work correctly for me too, so I'm just going to assume it's an issue I have in my own vimrc 🙃

Thanks for your help! I'll let you know if I find anything that needs to be addressed in vim-doge!
