### ISSUE TITLE
C++17 Nested Namespace Issue

### ISSUE THREAD

**Issue by XuhuiSun95** [kkoomen/vim-doge#316] opened 2021-10-26 20:01 UTC
I have experienced some issues with the nested namespace. The plugin seems like no response(or maybe trying to do something but not displaying/adding anything in the file).

I am not sure if this is the issue directly from the vim-doge, or maybe related to the underlay Tree sitter parser, can anyone help and clarify this?

If I change the code back to the old-style namespace, the plugin start working fine.

example, the first one will work, but not the second one:
```cpp
namespace A {
namespace B {
namespace C {

void helper1();

} // namespace C
} // namespace B
} // namespace A

namespace A::B::C {

void helper2();

} // namespace A::B::C
```

It seems like this specific issue start from three nested namespace.

**Comment by kkoomen** [comment] 2022-07-25 07:14
@XuhuiSun95 is this still an issue? I'm testing this again and it doesn't seem to be an issue.

**Comment by XuhuiSun95** [comment] 2022-07-28 18:31
> @XuhuiSun95 is this still an issue? I'm testing this again and it doesn't seem to be an issue.

I just pulled the latest master, and it still seems to have the same issue.

and actually, even worse, it seems non-nested namespace also only auto-complete docs on namespaces B and A in the example above but not C anymore.

was it because of something related to the actual compiler I am using in my env?

**Comment by XuhuiSun95** [comment] 2022-07-28 18:43
With a bit more investigation, I think the nested namespace issue is actually fixed, but the issue I mentioned above might be related to something else.

here is an example to reproduce:
```cpp
namespace A {
namespace B {
namespace C {
void helper();
}
} // namespace B
} // namespace A

```
this will not auto-complete the namespace of the current one, that's also the reason why the nested namespace currently still missing the namespace docs on my side.

However, once we add the docs for the function inside the namespace, like this
```cpp
namespace A {
namespace B {
namespace C {
/**
 * @brief [TODO:description]
 *
 */
void helper();
} // namespace C
} // namespace B
} // namespace A
```
that `namespace C` will be auto generated afterwards.

**Comment by XuhuiSun95** [comment] 2022-07-28 18:46
Another issue with nested namespace,

example like this
```cpp
namespace A::B::C {

void test();

}
```
for the nested namespace that has 3 or more, the doc gen doge_mapping also not working on this `void helper();` function on my side.

**Comment by kkoomen** [comment] 2022-07-28 19:08
@XuhuiSun95 Here's what I do:

Open `test.cpp` with the following contents:
```cpp
namespace A::B::C {

void test();

}
```

then on line 3 I trigger vim-doge and then I get the following result:

```cpp
namespace A::B::C {

/**
 * @brief [TODO:description]
 *
 */
void test();

}
```

This is what the output should be, right?

**Comment by XuhuiSun95** [comment] 2022-07-28 19:29
> ```c++
> namespace A::B::C {
> 
> void test();
> 
> }
> ```

@kkoomen 
![Peek 2022-07-28 12-25](https://user-images.githubusercontent.com/22652504/181621393-7662b169-761d-4db6-b9ec-7dac3e4f1e8c.gif)
The vim buffer is trying to do something, but there is nothing has been changed.

**Comment by kkoomen** [comment] 2022-07-28 19:30
Can you go to line 3 and type `:DogeGenerate`, does that do the exact same thing?

**Comment by kkoomen** [comment] 2022-07-28 19:33
Test it again with this vimrc. Open a new file `vim-doge.vimrc`, paste the following contents inside of it (make sure to change the path of the `/path/to/vim-doge` to your local path of where vim-doge is:

```vim
set nocompatible
set runtimepath^=/path/to/vim-doge
filetype plugin indent on
syntax on
set hidden
```
then run `vim -u vim-doge.vimrc`, go to line 3 and run `:DogeGenerate`, does this work?

If this works then perhaps there's another plugin conflicting on the same keybind.

**Comment by XuhuiSun95** [comment] 2022-07-28 20:28
> Test it again with this vimrc. Open a new file `vim-doge.vimrc`, paste the following contents inside of it (make sure to change the path of the `/path/to/vim-doge` to your local path of where vim-doge is):
> 
> ```viml
> set nocompatible
> set runtimepath^=/path/to/vim-doge
> filetype plugin indent on
> syntax on
> set hidden
> ```
> 
> then run `vim -u vim-doge.vimrc test.cpp`, go to line 3 and run `:DogeGenerate`, does this work?
> 
> If this works then perhaps there's another plugin conflicting on the same keybind, because this is not an issue in all the hundreds of tests this repository has, and I also can't reproduce this with a minimum vimrc.

@kkoomen 
Thanks for the instruction, however, the above setup is still not working on the same example.
Also, I can confirm that the above setting does work on python docs.

```
 xuhui@xuhui-LinuxWorkstation  ~  vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 01 2022 09:16:32)
Included patches: 1-2269, 3612, 3625, 3669, 3741
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_any_white
+arabic            +file_in_path      +mouse_urxvt       +tcl
+autocmd           +find_in_path      +mouse_xterm       +termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
+balloon_eval      -footer            -mzscheme          +termresponse
+balloon_eval_term +fork()            +netbeans_intg     +textobjects
+browse            +gettext           +num64             +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     +perl              +toolbar
+cindent           +job               +persistent_undo   +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           +python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          -ruby              +wildmenu
+cursorbind        +lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con_gui    +mksession         +smartindent       +X11
+diff              +modify_fname      +sound             -xfontset
+digraphs          +mouse             +spell             +xim
+dnd               +mouseshape        +startuptime       +xpm
-ebcdic            +mouse_dec         +statusline        +xsmp_interact
+emacs_tags        +mouse_gpm         -sun_workshop      +xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary
+extra_search      +mouse_sgr         -tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-9EpYYi/vim-8.1.2269=. -fstack-protector-strong -Wformat -Werror=format-security -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -Wl,-E  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lcanberra -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.30/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.8/config-3.8-x86_64-linux-gnu -lpython3.8 -lcrypt -lpthread -ldl -lutil -lm -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm
```
I am using the ubuntu20.04LTS with apt installed vim I believe.

**Comment by kkoomen** [comment] 2022-07-28 20:54
@XuhuiSun95 I will test tomorrow on an Ubuntu VM to try to reproduce this issue. In the meanwhile, can you try the following:

1. `cd` into the `vim-doge` directory
2. create `test.cpp` with the following contents:

```cpp
namespace A::B::C {

void test();

}
```
3. run `./bin/vim-doge test.cpp cpp 3 function_declarator`

The output should be:

```
$ ./bin/vim-doge test.cpp cpp 3 function_declarator
{"typeParameters":[],"name":"test","parameters":[],"returnType":"void","startPosition":2}
```

Is your output the same?

**Comment by XuhuiSun95** [comment] 2022-07-28 21:00
> 

@kkoomen 
test.cpp
```cpp
namespace A {

void test();

}
```
 xuhui@xuhui-LinuxWorkstation  ~/.vim_runtime/my_plugins/vim-doge   master  ./bin/vim-doge test.cpp cpp 3 function_declarator
{"typeParameters":[],"name":"test","parameters":[],"returnType":"void"}
```

test2.cpp
```cpp
namespace A::B::C {

void test();

}
```

```
 xuhui@xuhui-LinuxWorkstation  ~/.vim_runtime/my_plugins/vim-doge   master  ./bin/vim-doge test2.cpp cpp 3 function_declarator
```
return nothing

**Comment by kkoomen** [comment] 2022-07-28 21:09
@XuhuiSun95 Wait, can you check the `package.json` and check the current version of vim-doge? Make sure you're at the latest version because it doesn't seem to be the case. In case you need to update:

1. `cd` into vim-doge directory
2. pull latest version
3. run `rm -rf node_modules && npm install`
4. run `rm -rf bin`
5. open vim and run `call doge#install()`
6. open a new file `test.cpp` with the following contents
```cpp
namespace A {

void test();

}
```
7. run `./bin/vim-doge test.cpp cpp 3 function_declarator`
8. The output should be like so:

```
$ ./bin/vim-doge test.cpp cpp 3 function_declarator
{"typeParameters":[],"name":"test","parameters":[],"returnType":"void","startPosition":2}
```

**Comment by XuhuiSun95** [comment] 2022-07-28 21:44
@kkoomen 
That's it. 
Thanks for the help. I managed to pull the latest repo but did not run the `call doge#install()` again. The binary was outdated.

With this latest version, the no auto namespace close docs issue still exists when there are no docs for the function.

**Comment by kkoomen** [comment] 2022-07-28 21:47
> the no auto namespace close docs issue

What do you mean with this? Are you saying that although oh you have the latest version, you're still running into be issue?

**Comment by XuhuiSun95** [comment] 2022-07-28 21:49
> > the no auto namespace close docs issue
> 
> What do you mean with this? Are you saying that although oh you have the latest version, you're still running into be issue?

```cpp
namespace A::B::C {

void test();

}
```
this will not automatically add the `// namespace A::B::C` at the end 

unless we have something like 
```cpp
namespace A::B::C {

/**
 * @brief [TODO:description]
 *
 */
void test();

}
```

**Comment by kkoomen** [comment] 2022-07-29 06:30
> this will not automatically add the // namespace A::B::C at the end

True. This is something you can do by yourself, as this plugin won't do it because this plugin will only add documentation on top and not below. You can simply indent your code and use plugins like [indentLine](https://github.com/Yggdroot/indentLine) to easily see where a block of code starts and where its corresponding closing bracket ends.

You can make a [doc standard feature request](https://github.com/kkoomen/vim-doge/issues/new?assignees=&labels=enhancement&template=doc_standard.md&title=Add+%3Cdoc-standard%3E+doc+standard+for+%3Clanguage%3E) but I will only implement this if enough people like your post because even though I'm aware there are people that add a comment to the closing bracket, it isn't being done anymore because of the aforementioned reasons.

I will close this issue as the original problem isn't a problem.

**Closed by kkoomen** 2022-07-29 06:30 UTC
Labels: bug
