### ISSUE TITLE
Does not work on windows 

### ISSUE THREAD

**Issue by isfandyar01** [kkoomen/vim-doge#588] opened 2023-07-03 15:11 UTC
I am having trouble setting vim doge on windows.I got it working on accident on linux but on windows i have no luck.
I even tried npm install and npm run build in doge folder

**Comment by kkoomen** [comment] 2023-07-08 21:39
Hi.

Yes, unfortunately there are issues on windows because of node-gyp building issues, but I am working on vim-doge v4 which gets rid of all NodeJS code and has been rebuild from scratch in Rust. This allows docblocks to be generated way faster and supports all systems possible, including windows. The rewrite was done because of many reasons, one of them to support windows again, but unfortunately I didn't had time until a week ago.

Once v4 has been released, I'll mention it here as well to keep you updated.

**Comment by kkoomen** [comment] 2023-07-09 19:23
@isfandyar01 v4 has been released just now. Can you try to open vim, then run `:call doge#install()` and then test again?

**Comment by isfandyarIOT** [comment] 2023-07-10 08:20
sure testing now

**Comment by isfandyarIOT** [comment] 2023-07-10 08:29
does not work even when running command DogeGenerate numpy give me nothing

**Comment by kkoomen** [comment] 2023-07-10 17:42
@isfandyar01 I need more information than just "it's giving me nothing". 
- What shell are you using? 
- What is the output of `vim --version`?
- Does `bin/vim-doge-helper` exists inside your local vim-doge folder? (if not, run `:call doge#install()`)
- What code are you testing on? 

Please provide me with all information in order me to properly reproduce the problem you're facing.

**Comment by kkoomen** [comment] 2023-07-24 01:48
Fixed by #593

**Closed** 2023-07-24 01:49 UTC
Labels: question

**Comment by kkoomen** [comment] 2023-07-24 13:11
This fix has been released in v4.1.0, enjoy!
